### PR TITLE
Add Decimal Handling

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**

### CODE REVIEW

**Comment by unti1x** [comment]
I don't think adding an unnecessary dependency a good idea. If you wish it work with anything other than primitive types, it's probably better to create a protocol or somehow detect support of conversion functions in other way.

**Comment by xou** [comment]
I'm guessing that `decimal` is popular enough so it wouldn't hurt as much adding it as a dependency.
I'm a bit more worried though that implicitly casting a Decimal to an excel number might have unintended side-effects - loss of precision, for example, or lack of formatting options. I'm suspecting that the target audience for an arbitrary precision library would probably like to avoid the implicit conversion... (thoughts?)

**Comment by CharlesOkwuagwu** [comment]
> I'm a bit more worried though that implicitly casting a Decimal to an excel number might have unintended side-effects - loss of precision, for example, or lack of formatting options.

- Decimal lib gives up to 15 decimal places
- Formatting comes from your library, not from Decimal, in most cases aren't you doing to_string first before formatting?

**Comment by xou** [comment]
Hi Charles,

Sorry for leaving this pending for so long. To be honest, I have no use-case for the decimal library, so I can't really say much on what typical use-cases might be.

Upon revisiting this though, I do tend to agree with @unti1x that the dependency on `decimal` is too much, so I'd prefer not merging this for now. Sorry!

**Comment by CharlesOkwuagwu** [comment]
no problem

**Pull request closed without merging**
