### PR TITLE
row/col outline level (grouping) support

### PR DESCRIPTION
**Pull request by mtannaan**
Hi. Thank you for providing this wonderful library, which is so simple to use! (I also use Python's openpyxl, but tired of its messy API...)

I personally had a work where I had to group rows/columns, just like the following article:
https://oxen.tech/blog/grouping-excel/

I forked xlixlsx and made some changes to do this.
I'd appreciate it if you review and merge my changes so that everyone can use this feature via Hex!

Your comments and edits are very appreciated.

### CODE REVIEW

**Comment by xou** [comment]
Hi!

Thanks for adding this feature!
"Outline Levels" is unfortunately not trivial to understand without knowledge of how this is implemented (or the xlsx spec). I am wondering whether a better interface could take parameters such as (group_rows: [[1, 10], [3, 5, hide:true]]); and the outline levels (and "hidden" parameter) are then calculated automatically?

WDYT?

**Comment by mtannaan** [comment]
Thanks for the response!
Sounds great, we are "grouping rows" when using Excel, rather than "setting outline levels."
I'll make some edits to support this.

**Comment by mtannaan** [comment]
Changed `row/col_outline_levels` to `group_rows/columns` and added support for `:collapsed` option.
I'd be glad if you check this is aligned to your suggestion.

**Comment by xou** [comment]
Awesome, thanks for this!

**Pull request merged**
