### PR TITLE
Adding ability to lock panes in common configurations

### PR DESCRIPTION
**Pull request by mikebaldry**
Can now call `set_pane_freeze(sheet, row_idx, col_idx)`. Updated examples also

### CODE REVIEW

**Comment by unti1x** [comment]
That's fine, but how about another rows/cols?

**Comment by mikebaldry** [comment]
it was enough for me.

**Comment by unti1x** [comment]
Well, this library is not only for your purposes, is it? E.g., other documents may have 5-6 lines header. Also, you didn't write tests and docs for this behavior.

**Comment by xou** [comment]
Hi Mike,

First of all, thanks for the PR!

Is it maybe possible to make the freeze functionality slightly more generic (as @unti1x suggested), and make the :top_row etc. a convenience layer around the more generic functionality?

Also, would be great if you could integrate this into example.exs :)

Thanks!

**Comment by mikebaldry** [comment]
Have updated 👍

**Comment by unti1x** [comment]
Still there are no tests and docs. Please, don't forget about them.

**Comment by mikebaldry** [comment]
What do you mean docs? Also there is no tests for almost everything else either?

**Comment by unti1x** [comment]
> What do you mean docs? 
I mean examples for https://github.com/xou/elixlsx/blob/master/example.exs

> Also there is no tests for almost everything else either?
Yep, but we slowly work on them. And it's better not to make situation worse.

**Comment by xou** [comment]
Awesome, thank you!

**Pull request merged**
