### PR TITLE
updating elixir version and fixing deprecated methods

### PR DESCRIPTION
**Pull request by goravbhootra**
@Fabi755 @xou Travis CI failed as it is trying to run the test with older version of Elixir and OTP. They need to be fixed in CI.

### CODE REVIEW

**Comment by goravbhootra** [comment]
Addresses https://github.com/xou/elixlsx/issues/56

**Comment by unti1x** [comment]
Don't forget to change `.travis.yml` https://github.com/xou/elixlsx/blob/e2657cda3243e627de3dce14f6d7fe5dc5ac1f69/.travis.yml#L5-L6

**Comment by goravbhootra** [comment]
@unti1x thanks and done. should I squash the commits?

**Comment by unti1x** [comment]
It's not necessary: github supports squash'n'merge

**Comment by xou** [comment]
Thanks!

**Pull request merged**
